#!/bin/bash

echo "=== TESTING ASSEMBLER ==="

pushd . > /dev/null

cd "${0%/*}"
cd ../assembler

echo "=== OPCODES ==="
sbcl --noinform --load shell-entry-tests.lisp "opcodes"
echo "=== MACROS ==="
sbcl --noinform --load shell-entry-tests.lisp "macros"

popd > /dev/null
